### ISSUE TITLE
[Bug/Glitch] Ore Processing Upgrades not working on vanilla raw ore

### ISSUE THREAD

**Issue by Gojira-Tanaka** [Wilyicaro/BetterFurnacesReforged#102]
BetterFurnaces-1.19.4-0.1.6-fabric.jar

Quilt 0.19.2-beta.4

All of the Ore Processing Upgrades are not working on any of the vanilla ores, whether they be the actual block or the raw ore pieces. It isn't making multiples of the ore, only the amount of ore I have put in. I put in 8 pieces, I get 8 pieces, not 16 or 32 with the Ultimate Furnaces Addon Ore Processing Upgrade.

**Comment by Wilyicaro** [comment]
Sorry for this problem, because I test the BFR with other mods, I did not pay attention to the fact that the tags of all the raw ores are not native to the fabric, but are from mods like Tech Reborn and Modern Industrialization, I will add the tags at least of the vanilla ores to avoid this, and put an option to activate an unsafe way to test if it is a raw ore by its name
