### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by frenchpig** [Wilyicaro/BetterFurnacesReforged#104]
**Mod Version-Minecraft Version**

Mod Loader Version: Fabric 0.14.21
Minecraft Version: 1.20.1
Mod Version: 0.1.7

**Bug/Glitch Occurrence Context**

The upgrades past the Iron Furnace are unable to craft

**What happened wrong**
I tried to craft the steel upgrade, the steel furnace, and the gold furnace (using the iron furnace recipe) and neither of those where available. I put the items in the correct order, but the item wasnt in the crafted item area, I tried the 3 diferent recipes thinking that only one was bugged, but it seems that all of them has the same problem, making it unable to continue with the progression of the mod.

The iron to Gold upgrade works, so it should be possible to just skip the steel furnace and go directly to gold

**Comment by Wilyicaro** [comment]
The furnaces of Ultimate Furnaces are optional, the original progression of the mod is Iron->Gold->Diamond->Netherhot->Extreme, due to most of those found in it(Ultimate Furnaces) being made of materials that are found in specific mods and that need these mods to have their ores in the pattern of the common fabric tags

If you are using some other mod that adds the ores used in the recipe of the Ultimate Furnaces furnaces, try modifying through datapacks or changing the .jar file of the mod the recipe in .json of these furnaces to put the respective item of the mod, or you can simply add the item tag that is present in the recipe.

**Comment by Wilyicaro** [comment]
And also check the names of the items in the recipe, not just the appearance, it could be the conductor blocks of the BFR
