### ISSUE TITLE
upgrades don't work

### ISSUE THREAD

**Issue by Patatoso3** [Wilyicaro/BetterFurnacesReforged#18]
Hello! When I try to use the upgrades in the furnaces they do not perform their function. For example the "ore progressing update" does not duplicate the mineral nor is it spent. The version I play is 1.17.1 with forge 37.1.0 and mod version 1.4
 
 ![image](https://user-images.githubusercontent.com/96537613/147116034-024aff40-874b-41c0-b5f6-383e7f360657.png)

**Comment by Wilyicaro** [comment]
Of course it doesn't work with the raw ores from 1.18, otherwise it wouldn't be much OP, as they already drop more with the fortune enchantment on the pickaxe.

**Comment by Wilyicaro** [comment]
And I think it's very bad to jump to conclusions, saying that all upgrades don't work, with a simple casual test done by you

**Comment by Patatoso3** [comment]
I'm sorry. I didn't want it to look that way. I was just curious because I had seen that it worked before. I appreciate your answer friend

**Comment by Wilyicaro** [comment]
Mistakes always happen even friend, have a good game then!

**Comment by Patatoso3** [comment]
Hello friend again, I just want to ask you what the functions would be for those types of improvements and if the other upgrades also received a change. I appreciate your work since this mod I took up in its previous versions. I await your reply attentively.

**Comment by Wilyicaro** [comment]
I made small changes to all upgrades ported from the original mod, such as balancing the durability of the fuel efficiency upgrade and ore processing upgrade, the consumption of the liquid fuel Upgrade depends on which fluid is used, the energy upgrade only works in Extreme Forge, upgrades can only be placed in their own slot in the furnace/forge, etc.

**Comment by Patatoso3** [comment]
In 1.17 and 1.18, what is the use of the ore processing upgrade if it does not add vanilla to the minerals? Have a new use?

**Comment by Wilyicaro** [comment]
Simply, the ore processing upgrade works on any block ore, picked up now from 1.17 with silk touch, due to issues involving balancing this advantage

**Comment by Wilyicaro** [comment]
Its biggest advantage is with ores from other mods that have not yet adopted the drop of raw ores, or that only drop 1 ore even with the use of fortune

**Comment by Patatoso3** [comment]
Thank you very much for your patience to answer me hahaha

**Comment by Wilyicaro** [comment]
You're welcome ;)

**Comment by hypernova132** [comment]
I think if ore processing upgrade can't double the raw ores there is no reason to craft it. It's effectively useless because you get more ores simply by fortuning the ores. I'm gonna have to disagree with the suggestion letting it double raw pieces makes it OP. It would only be true if it was OP versus vanilla minecraft. But in vanilla minecraft you can make iron and gold farms. So it's not even OP versus vanilla.

But if for whatever reason you still think doubling raw ore pieces makes it OP, if the ore processing upgrade is gonna be part of the mod, there needs to be reason to craft it. You can nerf the ore processing upgrade so it works on raw ores as well as the ore blocks but it only has a certain chance of doubling the output.

Still though, I might just instead use other mods to process my raw ores.

**Comment by Wilyicaro** [comment]
There you have a good point, in the matter of being able to make farms of gold and iron in vanilla, which would make this upgrade useless, but it would still be strange for the upgrade to be able to duplicate block and raw ores. This upgrade was always kind of OP, because of the very simple crafting, so I think it was balanced in 1.17.1

**Comment by Wilyicaro** [comment]
I'll think about how best to make this upgrade more useful in vanilla

**Comment by hypernova132** [comment]
Thank you. You mentioned you thought it was always OP because of simple crafting. I only thought it was OP when combined with the original nether ores mod. But I'm also quite used to mods doubling the amounts of ores I get with very simple crafting. Still I have played with others where it is not so simple and liked it too. You could make it harder to craft. Netherite is a lot harder to obtain than diamonds are so maybe have the recipe require diamonds for the base one and netherite and blaze rods for the advanced one. Or something along the lines of adding a requirement that requires players to go to the nether and obtain something to craft it.

**Comment by Wilyicaro** [comment]
I'm going to add a new upgrade, which will exclusively duplicate raw ores, without the "cheap" version with durability
