### ISSUE TITLE
Game Crash (Block entity being ticked cobblestone_generator)

### ISSUE THREAD

**Issue by DJ1Silva** [Wilyicaro/BetterFurnacesReforged#44]
Hello sometimes game randomly crash and create a error log 
he game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=state, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{minecraft:void_air}
Exit Code: -1
[crash-2022-07-11_01.29.02-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/9079907/crash-2022-07-11_01.29.02-client.txt)
Its looks like its because cobblestone generator

**Comment by Wilyicaro** [comment]
I know where this bug is, it's related to when the block is broken the block entity is not removed, but could you tell me when this bug started, if it was after breaking the cobblestone generator and putting it in another position, or something else

**Comment by DJ1Silva** [comment]
> well its happen when server generating chunks its so rare but sometimes happen and another problem with cobblestone generator , all stone types dont generate what they say
(like stone icon makes obsidian and cobblestone icon make Deepslate)

**Comment by Wilyicaro** [comment]
This bug is very unusual, not to say that it is impossible, this case of the icon and generated block diverge does not occur for 2 updates, and this random crash of the cobblestone generator I have never seen occur, I always test the mod on a dedicated server and client, the only thing that I didn't test was breaking the block
![image](https://user-images.githubusercontent.com/81383021/178360366-931c14e2-b45d-49cb-9cf8-c9370feb6f1d.png)

**Comment by Wilyicaro** [comment]
Fixed in versions 1.19-1.0.6 and 1.18.2-1.2.7
