### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [Wilyicaro/BetterFurnacesReforged#82]
better furnaces version 0.2.2 crashes the game.

[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11072988/latest.log)
[rei.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11072990/rei.log)
[rei-issues.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11072991/rei-issues.log)
[crash-2023-03-26_23.22.51-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11072992/crash-2023-03-26_23.22.51-client.txt)

**Comment by Wilyicaro** [comment]
First of all, thanks for reporting the bug, this error/crash is caused by the system's default language, which probably has mismatched uppercase character conversion, which I should have anticipated when carelessly setting to convert the Enum names of the mod blocks to be registered from the default language. 

Test this for yourself, change your language if possible to English if you really want to use the mod by then, the fix will take a while to be released
